Repository exercism/elixir, pull requests merged in 2021-06, with the labels that each got.

#744 🤖 Add labels append file
  .appends/.github/labels.yml
Labels: v3-migration 🤖

#751 `guessing-game` cosmetic fix
  exercises/concept/guessing-game/.docs/instructions.md
  exercises/concept/guessing-game/.meta/exemplar.ex
  exercises/concept/guessing-game/test/guessing_game_test.exs
Labels: reputation/contributed_code/minor

#752 [#725] New practice exercise `pov`
  config.json
  exercises/practice/pov/.docs/instructions.md
  exercises/practice/pov/.formatter.exs
  exercises/practice/pov/.meta/config.json
  exercises/practice/pov/.meta/example.ex
  exercises/practice/pov/.meta/tests.toml
  exercises/practice/pov/lib/pov.ex
  exercises/practice/pov/mix.exs
  exercises/practice/pov/test/pov_test.exs
  exercises/practice/pov/test/test_helper.exs
Labels: reputation/contributed_code/major, v3

#753 [#723] New practice exercise `zebra-puzzle`
  config.json
  exercises/practice/zebra-puzzle/.docs/instructions.md
  exercises/practice/zebra-puzzle/.formatter.exs
  exercises/practice/zebra-puzzle/.meta/config.json
  exercises/practice/zebra-puzzle/.meta/example.ex
  exercises/practice/zebra-puzzle/.meta/tests.toml
  exercises/practice/zebra-puzzle/lib/zebra_puzzle.ex
  exercises/practice/zebra-puzzle/mix.exs
  exercises/practice/zebra-puzzle/test/test_helper.exs
  exercises/practice/zebra-puzzle/test/zebra_puzzle_test.exs
Labels: reputation/contributed_code/major

#754 🤖 Update labels
  .appends/.github/labels.yml
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: v3-migration 🤖

#755 [#724] New practice exercise `rational-numbers`
  config.json
  exercises/practice/rational-numbers/.docs/instructions.md
  exercises/practice/rational-numbers/.formatter.exs
  exercises/practice/rational-numbers/.meta/config.json
  exercises/practice/rational-numbers/.meta/example.ex
  exercises/practice/rational-numbers/.meta/tests.toml
  exercises/practice/rational-numbers/lib/rational_numbers.ex
  exercises/practice/rational-numbers/mix.exs
  exercises/practice/rational-numbers/test/rational_numbers_test.exs
  exercises/practice/rational-numbers/test/test_helper.exs
Labels: reputation/contributed_code/major, x:size/large

#756 [#726] New practice exercise `satellite`
  config.json
  exercises/practice/satellite/.docs/instructions.md
  exercises/practice/satellite/.formatter.exs
  exercises/practice/satellite/.meta/config.json
  exercises/practice/satellite/.meta/example.ex
  exercises/practice/satellite/.meta/tests.toml
  exercises/practice/satellite/lib/satellite.ex
  exercises/practice/satellite/mix.exs
  exercises/practice/satellite/test/satellite_test.exs
  exercises/practice/satellite/test/test_helper.exs
Labels: reputation/contributed_code/major, x:size/large

#758 Change return types in practice exercise `pov`
  exercises/practice/pov/.meta/example.ex
  exercises/practice/pov/lib/pov.ex
  exercises/practice/pov/test/pov_test.exs
Labels: reputation/contributed_code/minor, x:size/small

#762 Set a specific range of supported versions
  CONTRIBUTING.md
  README.md
Labels: reputation/contributed_code/minor, x:size/tiny

#769 [#765] New practice exercise `complex-numbers`
  config.json
  exercises/practice/complex-numbers/.docs/instructions.append.md
  exercises/practice/complex-numbers/.docs/instructions.md
  exercises/practice/complex-numbers/.formatter.exs
  exercises/practice/complex-numbers/.meta/config.json
  exercises/practice/complex-numbers/.meta/example.ex
  exercises/practice/complex-numbers/.meta/tests.toml
  exercises/practice/complex-numbers/lib/complex_numbers.ex
  exercises/practice/complex-numbers/mix.exs
  exercises/practice/complex-numbers/test/complex_numbers_test.exs
  exercises/practice/complex-numbers/test/test_helper.exs
Labels: reputation/contributed_code/major, x:size/large

#773 [#763] New practice exercise `affine-cipher`
  config.json
  exercises/practice/affine-cipher/.docs/instructions.md
  exercises/practice/affine-cipher/.formatter.exs
  exercises/practice/affine-cipher/.meta/config.json
  exercises/practice/affine-cipher/.meta/example.ex
  exercises/practice/affine-cipher/.meta/tests.toml
  exercises/practice/affine-cipher/lib/affine_cipher.ex
  exercises/practice/affine-cipher/mix.exs
  exercises/practice/affine-cipher/test/affine_cipher_test.exs
  exercises/practice/affine-cipher/test/test_helper.exs
Labels: reputation/contributed_code/major, x:size/large

#774 Bootstrap practice exercises
  bin/bootstrap_practice_exercise.exs
Labels: reputation/contributed_code/major, x:size/large

#778 [#764] New practice exercise `book-store`
  config.json
  exercises/practice/book-store/.docs/instructions.md
  exercises/practice/book-store/.formatter.exs
  exercises/practice/book-store/.meta/config.json
  exercises/practice/book-store/.meta/example.ex
  exercises/practice/book-store/.meta/tests.toml
  exercises/practice/book-store/lib/book_store.ex
  exercises/practice/book-store/mix.exs
  exercises/practice/book-store/test/book_store_test.exs
  exercises/practice/book-store/test/test_helper.exs
Labels: x:size/large

#777 [#767] New practice exercise `darts`
  config.json
  exercises/practice/darts/.docs/hints.md
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/darts/.formatter.exs
  exercises/practice/darts/.meta/config.json
  exercises/practice/darts/.meta/example.ex
  exercises/practice/darts/.meta/tests.toml
  exercises/practice/darts/lib/darts.ex
  exercises/practice/darts/mix.exs
  exercises/practice/darts/test/darts_test.exs
  exercises/practice/darts/test/test_helper.exs
Labels: x:size/large

#776 [#768] New practice exercise `go-counting`
  config.json
  exercises/practice/go-counting/.docs/instructions.md
  exercises/practice/go-counting/.formatter.exs
  exercises/practice/go-counting/.meta/config.json
  exercises/practice/go-counting/.meta/example.ex
  exercises/practice/go-counting/.meta/tests.toml
  exercises/practice/go-counting/lib/go_counting.ex
  exercises/practice/go-counting/mix.exs
  exercises/practice/go-counting/test/go_counting_test.exs
  exercises/practice/go-counting/test/test_helper.exs
Labels: reputation/contributed_code/major, x:size/large

#775 [#766] New practice exercise `circular-buffer`
  config.json
  exercises/practice/circular-buffer/.docs/instructions.md
  exercises/practice/circular-buffer/.formatter.exs
  exercises/practice/circular-buffer/.meta/config.json
  exercises/practice/circular-buffer/.meta/example.ex
  exercises/practice/circular-buffer/.meta/tests.toml
  exercises/practice/circular-buffer/lib/circular_buffer.ex
  exercises/practice/circular-buffer/mix.exs
  exercises/practice/circular-buffer/test/circular_buffer_test.exs
  exercises/practice/circular-buffer/test/test_helper.exs
Labels: reputation/contributed_code/major, x:size/large

#780 New practice exercise `food-chain`
  config.json
  exercises/practice/food-chain/.docs/instructions.md
  exercises/practice/food-chain/.formatter.exs
  exercises/practice/food-chain/.meta/config.json
  exercises/practice/food-chain/.meta/example.ex
  exercises/practice/food-chain/.meta/tests.toml
  exercises/practice/food-chain/lib/food_chain.ex
  exercises/practice/food-chain/mix.exs
  exercises/practice/food-chain/test/food_chain_test.exs
  exercises/practice/food-chain/test/test_helper.exs
Labels: x:size/large

#794 Random fixes for concept exercises
  concepts/booleans/about.md
  exercises/concept/log-level/lib/log_level.ex
Labels: x:size/tiny

#796 library-fees: Explicitely mention that Ghana doesn't use DST
  exercises/concept/library-fees/.docs/instructions.md
Labels: x:size/tiny

#799 Use new reputation labels in automated comment
  .github/pr-commenter.yml
Labels: x:size/tiny

#795 New practice exercise `sgf-parsing`
  config.json
  exercises/practice/sgf-parsing/.docs/instructions.md
  exercises/practice/sgf-parsing/.formatter.exs
  exercises/practice/sgf-parsing/.meta/config.json
  exercises/practice/sgf-parsing/.meta/example.ex
  exercises/practice/sgf-parsing/.meta/tests.toml
  exercises/practice/sgf-parsing/lib/sgf_parsing.ex
  exercises/practice/sgf-parsing/mix.exs
  exercises/practice/sgf-parsing/test/sgf_parsing_test.exs
  exercises/practice/sgf-parsing/test/test_helper.exs
Labels: x:size/large

#798 New practice exercise `variable-length-quantity`
  config.json
  exercises/practice/variable-length-quantity/.docs/instructions.md
  exercises/practice/variable-length-quantity/.formatter.exs
  exercises/practice/variable-length-quantity/.meta/config.json
  exercises/practice/variable-length-quantity/.meta/example.ex
  exercises/practice/variable-length-quantity/.meta/tests.toml
  exercises/practice/variable-length-quantity/lib/variable_length_quantity.ex
  exercises/practice/variable-length-quantity/mix.exs
  exercises/practice/variable-length-quantity/test/test_helper.exs
  exercises/practice/variable-length-quantity/test/variable_length_quantity_test.exs
Labels: x:size/large
