Repository exercism/elixir, pull requests merged in 2021-07, with the labels that each got.

#805 Exercise fix: Change colors to atoms and add @doc in `resistor-color`
  exercises/practice/resistor-color/.meta/example.ex
  exercises/practice/resistor-color/lib/resistor_color.ex
  exercises/practice/resistor-color/test/resistor_color_test.exs
Labels: x:size/small

#801 New practice exercise `resistor-color-trio`
  config.json
  exercises/practice/resistor-color-trio/.docs/instructions.md
  exercises/practice/resistor-color-trio/.formatter.exs
  exercises/practice/resistor-color-trio/.meta/config.json
  exercises/practice/resistor-color-trio/.meta/example.ex
  exercises/practice/resistor-color-trio/lib/resistor_color_trio.ex
  exercises/practice/resistor-color-trio/mix.exs
  exercises/practice/resistor-color-trio/test/resistor_color_trio_test.exs
  exercises/practice/resistor-color-trio/test/test_helper.exs
Labels: x:size/large

#807 Simplify resistor-color
  config.json
  exercises/practice/resistor-color/.meta/design.md
  exercises/practice/resistor-color/.meta/example.ex
  exercises/practice/resistor-color/.meta/tests.toml
  exercises/practice/resistor-color/lib/resistor_color.ex
  exercises/practice/resistor-color/test/resistor_color_test.exs
Labels: x:size/tiny

#809 Change return datetime to date
  exercises/concept/library-fees/.docs/hints.md
  exercises/concept/library-fees/.docs/instructions.md
  exercises/concept/library-fees/.meta/exemplar.ex
  exercises/concept/library-fees/lib/library_fees.ex
  exercises/concept/library-fees/test/library_fees_test.exs
Labels: x:size/small

#797 New practice exercise `square-root`
  config.json
  exercises/practice/square-root/.docs/instructions.append.md
  exercises/practice/square-root/.docs/instructions.md
  exercises/practice/square-root/.formatter.exs
  exercises/practice/square-root/.meta/config.json
  exercises/practice/square-root/.meta/example.ex
  exercises/practice/square-root/lib/square_root.ex
  exercises/practice/square-root/mix.exs
  exercises/practice/square-root/test/square_root_test.exs
  exercises/practice/square-root/test/test_helper.exs
Labels: x:size/large

#808 [#792] New practice exercise `two-bucket`
  config.json
  exercises/practice/two-bucket/.docs/instructions.md
  exercises/practice/two-bucket/.formatter.exs
  exercises/practice/two-bucket/.meta/config.json
  exercises/practice/two-bucket/.meta/example.ex
  exercises/practice/two-bucket/.meta/tests.toml
  exercises/practice/two-bucket/lib/two_bucket.ex
  exercises/practice/two-bucket/mix.exs
  exercises/practice/two-bucket/test/test_helper.exs
  exercises/practice/two-bucket/test/two_bucket_test.exs
Labels: x:size/large

#804 [#793] New practice exercise `word-search`
  config.json
  exercises/practice/word-search/.docs/instructions.md
  exercises/practice/word-search/.formatter.exs
  exercises/practice/word-search/.meta/config.json
  exercises/practice/word-search/.meta/example.ex
  exercises/practice/word-search/.meta/tests.toml
  exercises/practice/word-search/lib/word_search.ex
  exercises/practice/word-search/mix.exs
  exercises/practice/word-search/test/test_helper.exs
  exercises/practice/word-search/test/word_search_test.exs
Labels: x:size/large

#812 Missing tests.toml
  exercises/practice/resistor-color-trio/.meta/tests.toml
  exercises/practice/square-root/.meta/tests.toml
Labels: x:size/small

#814 [#788] New practice exercise `house`
  config.json
  exercises/practice/house/.docs/instructions.md
  exercises/practice/house/.formatter.exs
  exercises/practice/house/.meta/config.json
  exercises/practice/house/.meta/example.ex
  exercises/practice/house/.meta/tests.toml
  exercises/practice/house/lib/house.ex
  exercises/practice/house/mix.exs
  exercises/practice/house/test/house_test.exs
  exercises/practice/house/test/test_helper.exs
Labels: x:module/practice-exercise, x:size/medium

#815 [#786] New practice exercise `proverb`
  config.json
  exercises/practice/proverb/.docs/instructions.md
  exercises/practice/proverb/.formatter.exs
  exercises/practice/proverb/.meta/config.json
  exercises/practice/proverb/.meta/example.ex
  exercises/practice/proverb/.meta/tests.toml
  exercises/practice/proverb/lib/proverb.ex
  exercises/practice/proverb/mix.exs
  exercises/practice/proverb/test/proverb_test.exs
  exercises/practice/proverb/test/test_helper.exs
Labels: x:module/practice-exercise, x:size/medium

#825 Remove empty `## Analyzer` sections from design.mds
  exercises/concept/community-garden/.meta/design.md
  exercises/concept/date-parser/.meta/design.md
  exercises/concept/high-school-sweetheart/.meta/design.md
  exercises/concept/library-fees/.meta/design.md
  exercises/concept/remote-control-car/.meta/design.md
  exercises/concept/rpn-calculator/.meta/design.md
Labels: x:size/tiny

#816 Fix test compilation warnings unrelated to task_id
  exercises/concept/bread-and-potions/test/rpg_test.exs
  exercises/concept/freelancer-rates/.meta/config.json
  exercises/concept/stack-underflow/test/rpn_calculator/exception_test.exs
  exercises/practice/zebra-puzzle/test/zebra_puzzle_test.exs
Labels: x:size/tiny

#823 Use comments instead of RuntimeErrors in conccept exercise stubs
  exercises/concept/basketball-website/lib/basketball_website.ex
  exercises/concept/bird-count/lib/bird_count.ex
  exercises/concept/boutique-inventory/lib/boutique_inventory.ex
  exercises/concept/boutique-suggestions/lib/boutique_suggestions.ex
  exercises/concept/captains-log/lib/captains_log.ex
  exercises/concept/chessboard/lib/chessboard.ex
  exercises/concept/community-garden/lib/community_garden.ex
  exercises/concept/date-parser/lib/date_parser.ex
  exercises/concept/dna-encoding/lib/dna.ex
  exercises/concept/file-sniffer/lib/file_sniffer.ex
  exercises/concept/freelancer-rates/lib/freelancer_rates.ex
  exercises/concept/german-sysadmin/lib/username.ex
  exercises/concept/guessing-game/lib/guessing_game.ex
  exercises/concept/high-school-sweetheart/lib/high_school_sweetheart.ex
  exercises/concept/high-score/lib/high_score.ex
  exercises/concept/kitchen-calculator/lib/kitchen_calculator.ex
  exercises/concept/language-list/lib/language_list.ex
  exercises/concept/library-fees/lib/library_fees.ex
  exercises/concept/log-level/lib/log_level.ex
  exercises/concept/lucas-numbers/lib/lucas_numbers.ex
  exercises/concept/mensch-aergere-dich-nicht/lib/mensch_aergere_dich_nicht.ex
  exercises/concept/name-badge/lib/name_badge.ex
  exercises/concept/newsletter/lib/newsletter.ex
  exercises/concept/pacman-rules/lib/rules.ex
  exercises/concept/remote-control-car/lib/remote_control_car.ex
  exercises/concept/rpg-character-sheet/lib/rpg/character_sheet.ex
  exercises/concept/rpn-calculator-inspection/lib/rpn_calculator_inspection.ex
  exercises/concept/rpn-calculator-output/lib/rpn_calculator/output.ex
  exercises/concept/rpn-calculator/lib/rpn_calculator.ex
  exercises/concept/secrets/lib/secrets.ex
  exercises/concept/take-a-number/lib/take_a_number.ex
  exercises/concept/wine-cellar/lib/wine_cellar.ex
Labels: x:size/tiny

#822 Reorder concept exercises to follow concept tree order
  config.json
Labels: x:size/tiny

#826 Use @tag instead of custom attribute for task id
  .github/pr-commenter.yml
  exercises/concept/basketball-website/test/basketball_website_test.exs
  exercises/concept/bird-count/test/bird_count_test.exs
  exercises/concept/boutique-inventory/test/boutique_inventory_test.exs
  exercises/concept/boutique-suggestions/test/boutique_suggestions_test.exs
  exercises/concept/bread-and-potions/test/rpg_test.exs
  exercises/concept/captains-log/test/captains_log_test.exs
  exercises/concept/chessboard/test/chessboard_test.exs
  exercises/concept/city-office/test/form_test.exs
  exercises/concept/community-garden/test/community_garden_test.exs
  exercises/concept/date-parser/test/date_parser_test.exs
  exercises/concept/dna-encoding/test/dna_test.exs
  exercises/concept/file-sniffer/test/file_sniffer_test.exs
  exercises/concept/freelancer-rates/test/freelancer_rates_test.exs
  exercises/concept/german-sysadmin/test/username_test.exs
  exercises/concept/guessing-game/test/guessing_game_test.exs
  exercises/concept/high-school-sweetheart/test/high_school_sweetheart_test.exs
  exercises/concept/high-score/test/high_score_test.exs
  exercises/concept/kitchen-calculator/test/kitchen_calculator_test.exs
  exercises/concept/language-list/test/language_list_test.exs
  exercises/concept/lasagna/test/lasagna_test.exs
  exercises/concept/library-fees/test/library_fees_test.exs
  exercises/concept/log-level/test/log_level_test.exs
  exercises/concept/lucas-numbers/test/lucas_numbers_test.exs
  exercises/concept/name-badge/test/name_badge_test.exs
  exercises/concept/need-for-speed/test/need_for_speed_test.exs
  exercises/concept/newsletter/test/newsletter_test.exs
  exercises/concept/pacman-rules/test/rules_test.exs
  exercises/concept/remote-control-car/test/remote_control_car_test.exs
  exercises/concept/rpg-character-sheet/test/rpg/character_sheet_test.exs
  exercises/concept/rpn-calculator-inspection/test/rpn_calculator_inspection_test.exs
  exercises/concept/rpn-calculator-output/test/rpn_calculator/output_test.exs
  exercises/concept/rpn-calculator/test/rpn_calculator_test.exs
  exercises/concept/secrets/test/secrets_test.exs
  exercises/concept/stack-underflow/test/rpn_calculator/exception_test.exs
  exercises/concept/take-a-number/test/take_a_number_test.exs
  exercises/concept/wine-cellar/test/wine_cellar_test.exs
Labels: x:size/tiny

#830 Point language-list hints to specific functions
  concepts/lists/about.md
  concepts/lists/introduction.md
  exercises/concept/language-list/.docs/hints.md
  exercises/concept/language-list/.docs/introduction.md
Labels: x:size/small

#835 Do not care about emtpy lists in language-list
  exercises/concept/language-list/.docs/instructions.md
  exercises/concept/language-list/test/language_list_test.exs
Labels: x:size/small

#831 New practice exercise `rest-api`
  bin/bootstrap_practice_exercise.exs
  config.json
Labels: x:size/large

#837 commented pending tag typo fix
  exercises/practice/pascals-triangle/test/pascals_triangle_test.exs
Labels: x:size/tiny

#836 Correct example in log-level instructions
  exercises/concept/log-level/.docs/instructions.md
Labels: x:size/tiny

#838 Add icons to key features
  config.json
Labels: x:size/small, x:size/tiny

#842 Prefer Integer.pow over :math.pow |> round
  exercises/practice/diffie-hellman/.docs/hints.md
Labels: x:size/small
