Repository exercism/elixir, pull requests merged in 2021-11, with the labels that each got.

#984 Bring book-store up to date with canonical-data
  exercises/practice/book-store/.meta/tests.toml
  exercises/practice/book-store/test/book_store_test.exs
Labels: x:size/small

#985 Bring luhn up to date with canonical-data
  exercises/practice/luhn/.meta/tests.toml
  exercises/practice/luhn/test/luhn_test.exs
Labels: x:size/small

#986 Bring rational-numbers up to date with canonical-data
  exercises/practice/rational-numbers/.meta/tests.toml
  exercises/practice/rational-numbers/test/rational_numbers_test.exs
Labels: x:size/tiny

#987 Bring resistor-color-duo up to date with canonical-data
  exercises/practice/resistor-color-duo/.meta/tests.toml
  exercises/practice/resistor-color-duo/test/resistor_color_duo_test.exs
Labels: x:size/small

#994 🤖 Remove obsolete `maintainers.json` file
  .github/CODEOWNERS
  config/maintainers.json
Labels: x:size/tiny

#930 New concept exercise `top-secret` (concept: `ast`)
  concepts/ast/.meta/config.json
  concepts/ast/about.md
  concepts/ast/introduction.md
  concepts/ast/links.json
  config.json
  exercises/concept/top-secret/.docs/hints.md
  exercises/concept/top-secret/.docs/instructions.md
  exercises/concept/top-secret/.docs/introduction.md
  exercises/concept/top-secret/.formatter.exs
  exercises/concept/top-secret/.gitignore
  exercises/concept/top-secret/.meta/config.json
  exercises/concept/top-secret/.meta/design.md
  exercises/concept/top-secret/.meta/exemplar.ex
  exercises/concept/top-secret/lib/top_secret.ex
  exercises/concept/top-secret/mix.exs
  exercises/concept/top-secret/test/test_helper.exs
  exercises/concept/top-secret/test/top_secret_test.exs
Labels: x:size/large

#996 Added an example using strings as keys.
  concepts/access-behaviour/about.md
  concepts/access-behaviour/introduction.md
  exercises/concept/basketball-website/.docs/introduction.md
Labels: x:size/small

#997 Explain the return of the get_counter function
  exercises/concept/new-passport/.docs/instructions.md
Labels: x:size/small

#998 Fix secret_test.ex so that test descriptions match the tests
  exercises/concept/secrets/test/secrets_test.exs
Labels: x:size/small

#1006 fix(bird-count .docs): grammer issue question 5 GH-1005
  exercises/concept/bird-count/.docs/instructions.md
Labels: x:size/small

#1000 Refactor anonymous functions into captured functions
  exercises/concept/rpn-calculator-inspection/.meta/exemplar.ex
  exercises/practice/acronym/.meta/example.ex
  exercises/practice/difference-of-squares/.meta/example.ex
  exercises/practice/grep/.meta/example.ex
  exercises/practice/largest-series-product/.meta/example.ex
  exercises/practice/list-ops/.meta/example.ex
  exercises/practice/ocr-numbers/.meta/example.ex
  exercises/practice/pythagorean-triplet/.meta/example.ex
  exercises/practice/rna-transcription/.meta/example.ex
  exercises/practice/transpose/.meta/example.ex
Labels: x:action/improve, x:module/concept-exercise, x:type/coding, x:size/small, x:module/practice-exercise

#1007 Update instructions for resistor-color
  exercises/practice/resistor-color/.docs/instructions.append.md
Labels: x:size/small

#1009 Add www to links to erlang doc
  concepts/dates-and-time/about.md
  concepts/erlang-libraries/about.md
  concepts/erlang-libraries/introduction.md
  concepts/erlang-libraries/links.json
  concepts/pids/about.md
  concepts/randomness/about.md
  concepts/randomness/links.json
  concepts/tasks/about.md
  concepts/typespecs/about.md
  docs/TESTS.md
  exercises/concept/captains-log/.docs/hints.md
  exercises/concept/captains-log/.docs/introduction.md
Labels: x:size/small

#1010 Update `parallel-letter-frequency` to actually be parallel
  exercises/practice/parallel-letter-frequency/.meta/config.json
  exercises/practice/parallel-letter-frequency/.meta/example.ex
Labels: x:size/small, x:module/practice-exercise
