Repository exercism/elixir, pull requests merged in 2021-03, with the labels that each got.

#598 Update `tests.toml` and remove `version` file for exercises that are up to date with canonical data
  exercises/practice/accumulate/.meta/version
  exercises/practice/acronym/.meta/version
  exercises/practice/allergies/.meta/version
  exercises/practice/alphametics/.meta/version
  exercises/practice/anagram/.meta/version
  exercises/practice/anagram/test/anagram_test.exs
  exercises/practice/armstrong-numbers/.meta/version
  exercises/practice/armstrong-numbers/test/armstrong_number_test.exs
  exercises/practice/atbash-cipher/.meta/version
  exercises/practice/bank-account/.meta/version
  exercises/practice/beer-song/.meta/version
  exercises/practice/binary-search/.meta/version
  exercises/practice/bob/.meta/version
  exercises/practice/bowling/.meta/version
  exercises/practice/collatz-conjecture/.meta/version
  exercises/practice/diffie-hellman/.meta/tests.toml
  exercises/practice/diffie-hellman/.meta/version
  exercises/practice/dominoes/.meta/version
  exercises/practice/dot-dsl/.meta/version
  exercises/practice/grains/.meta/version
  exercises/practice/ocr-numbers/.meta/version
  exercises/practice/ocr-numbers/test/ocr_numbers_test.exs
  exercises/practice/parallel-letter-frequency/.meta/version
  exercises/practice/perfect-numbers/.meta/version
  exercises/practice/poker/.meta/version
  exercises/practice/queen-attack/.meta/version
  exercises/practice/resistor-color/.meta/version
  exercises/practice/roman-numerals/.meta/version
  exercises/practice/rotational-cipher/.meta/version
  exercises/practice/run-length-encoding/.meta/version
  exercises/practice/say/.meta/version
  exercises/practice/scale-generator/.meta/version
  exercises/practice/secret-handshake/.meta/version
  exercises/practice/simple-linked-list/.meta/version
  exercises/practice/spiral-matrix/.meta/version
  exercises/practice/strain/.meta/version
Labels: canonical sync 🔄

#661 Bring `wordy` up to date with canonical data
  exercises/practice/wordy/.meta/example.ex
  exercises/practice/wordy/.meta/version
  exercises/practice/wordy/test/wordy_test.exs
Labels: canonical sync 🔄

#669 Bring `simple-cipher` up to date with canonical data
  config.json
  exercises/practice/simple-cipher/.meta/design.md
  exercises/practice/simple-cipher/.meta/example.ex
  exercises/practice/simple-cipher/.meta/tests.toml
  exercises/practice/simple-cipher/.meta/version
  exercises/practice/simple-cipher/lib/simple_cipher.ex
  exercises/practice/simple-cipher/mix.exs
  exercises/practice/simple-cipher/test/simple_cipher_test.exs
Labels: canonical sync 🔄

#643 Bring `pythagorean-triplet` up to date with canonical data
  config.json
  exercises/practice/pythagorean-triplet/.meta/example.ex
  exercises/practice/pythagorean-triplet/.meta/version
  exercises/practice/pythagorean-triplet/lib/triplet.ex
  exercises/practice/pythagorean-triplet/test/triplet_test.exs
Labels: canonical sync 🔄

#688 [v3] new concept exercise: lucas-numbers (streams)
  config.json
  exercises/concept/log-level/.meta/config.json
  exercises/concept/lucas-numbers/.docs/hints.md
  exercises/concept/lucas-numbers/.docs/instructions.md
  exercises/concept/lucas-numbers/.docs/introduction.md
  exercises/concept/lucas-numbers/.formatter.exs
  exercises/concept/lucas-numbers/.gitignore
  exercises/concept/lucas-numbers/.meta/config.json
  exercises/concept/lucas-numbers/.meta/design.md
  exercises/concept/lucas-numbers/.meta/exemplar.ex
  exercises/concept/lucas-numbers/lib/lucas_numbers.ex
  exercises/concept/lucas-numbers/mix.exs
  exercises/concept/lucas-numbers/test/lucas_numbers_test.exs
  exercises/concept/lucas-numbers/test/test_helper.exs
Labels: v3

#691 🤖 Add docs configuration
  docs/config.json
Labels: v3-migration 🤖

#696 🤖 Flatten authors and contributors in .meta/config.json files
  exercises/concept/basketball-website/.meta/config.json
  exercises/concept/bird-count/.meta/config.json
  exercises/concept/boutique-inventory/.meta/config.json
  exercises/concept/boutique-suggestions/.meta/config.json
  exercises/concept/bread-and-potions/.meta/config.json
  exercises/concept/captains-log/.meta/config.json
  exercises/concept/chessboard/.meta/config.json
  exercises/concept/community-garden/.meta/config.json
  exercises/concept/date-parser/.meta/config.json
  exercises/concept/dna-encoding/.meta/config.json
  exercises/concept/file-sniffer/.meta/config.json
  exercises/concept/freelancer-rates/.meta/config.json
  exercises/concept/german-sysadmin/.meta/config.json
  exercises/concept/guessing-game/.meta/config.json
  exercises/concept/high-school-sweetheart/.meta/config.json
  exercises/concept/high-score/.meta/config.json
  exercises/concept/kitchen-calculator/.meta/config.json
  exercises/concept/language-list/.meta/config.json
  exercises/concept/lasagna/.meta/config.json
  exercises/concept/library-fees/.meta/config.json
  exercises/concept/log-level/.meta/config.json
  exercises/concept/lucas-numbers/.meta/config.json
  exercises/concept/mensch-aergere-dich-nicht/.meta/config.json
  exercises/concept/name-badge/.meta/config.json
  exercises/concept/newsletter/.meta/config.json
  exercises/concept/pacman-rules/.meta/config.json
  exercises/concept/remote-control-car/.meta/config.json
  exercises/concept/rpg-character-sheet/.meta/config.json
  exercises/concept/rpn-calculator-inspection/.meta/config.json
  exercises/concept/rpn-calculator-output/.meta/config.json
  exercises/concept/rpn-calculator/.meta/config.json
  exercises/concept/secrets/.meta/config.json
  exercises/concept/stack-underflow/.meta/config.json
  exercises/concept/take-a-number/.meta/config.json
  exercises/concept/wine-cellar/.meta/config.json
Labels: v3-migration 🤖

#693 New concept exercise `city-office` (`docs` and `typespecs`)
  concepts/basics/about.md
  concepts/basics/introduction.md
  concepts/docs/about.md
  concepts/docs/introduction.md
  concepts/docs/links.json
  concepts/typespecs/about.md
  concepts/typespecs/introduction.md
  concepts/typespecs/links.json
  config.json
  exercises/concept/city-office/.docs/hints.md
  exercises/concept/city-office/.docs/instructions.md
  exercises/concept/city-office/.docs/introduction.md
  exercises/concept/city-office/.formatter.exs
  exercises/concept/city-office/.gitignore
  exercises/concept/city-office/.meta/config.json
  exercises/concept/city-office/.meta/design.md
  exercises/concept/city-office/.meta/exemplar.ex
  exercises/concept/city-office/lib/form.ex
  exercises/concept/city-office/mix.exs
  exercises/concept/city-office/test/form_test.exs
  exercises/concept/city-office/test/test_helper.exs
  exercises/concept/lasagna/.docs/introduction.md
Labels: reputation/contributed_code/major

#699 shorten practices entries for `enum` and `strings`
  config.json
Labels: reputation/contributed_code/minor

#700 Add test for `list-ops`
  exercises/practice/list-ops/test/list_ops_test.exs
Labels: enhancement ⭐️, reputation/contributed_code/minor
