Repository exercism/elixir, pull requests merged in 2021-04, with the labels that each got.

#702 🤖 Add .meta/config.json file for concepts
  concepts/access-behaviour/.meta/config.json
  concepts/agent/.meta/config.json
  concepts/anonymous-functions/.meta/config.json
  concepts/atoms/.meta/config.json
  concepts/basics/.meta/config.json
  concepts/binaries/.meta/config.json
  concepts/bit-manipulation/.meta/config.json
  concepts/bitstrings/.meta/config.json
  concepts/booleans/.meta/config.json
  concepts/case/.meta/config.json
  concepts/charlists/.meta/config.json
  concepts/cond/.meta/config.json
  concepts/dates-and-time/.meta/config.json
  concepts/default-arguments/.meta/config.json
  concepts/docs/.meta/config.json
  concepts/dynamic-dispatch/.meta/config.json
  concepts/enum/.meta/config.json
  concepts/erlang-libraries/.meta/config.json
  concepts/errors/.meta/config.json
  concepts/exceptions/.meta/config.json
  concepts/file/.meta/config.json
  concepts/floating-point-numbers/.meta/config.json
  concepts/guards/.meta/config.json
  concepts/if/.meta/config.json
  concepts/integers/.meta/config.json
  concepts/io/.meta/config.json
  concepts/keyword-lists/.meta/config.json
  concepts/links/.meta/config.json
  concepts/list-comprehensions/.meta/config.json
  concepts/lists/.meta/config.json
  concepts/maps/.meta/config.json
  concepts/module-attributes-as-constants/.meta/config.json
  concepts/multiple-clause-functions/.meta/config.json
  concepts/nil/.meta/config.json
  concepts/pattern-matching/.meta/config.json
  concepts/pids/.meta/config.json
  concepts/pipe-operator/.meta/config.json
  concepts/processes/.meta/config.json
  concepts/protocols/.meta/config.json
  concepts/randomness/.meta/config.json
  concepts/ranges/.meta/config.json
  concepts/recursion/.meta/config.json
  concepts/regular-expressions/.meta/config.json
  concepts/streams/.meta/config.json
  concepts/strings/.meta/config.json
  concepts/structs/.meta/config.json
  concepts/tail-call-recursion/.meta/config.json
  concepts/tasks/.meta/config.json
  concepts/try-rescue-else-after/.meta/config.json
  concepts/try-rescue/.meta/config.json
  concepts/tuples/.meta/config.json
  concepts/typespecs/.meta/config.json
  config.json
  exercises/concept/newsletter/.meta/config.json
Labels: v3-migration 🤖

#706 Fix sync-labels syntax error
  .github/workflows/sync-labels.yml
Labels: reputation/contributed_code/minor

#707 Fix label-syncer again :)
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: reputation/contributed_code/minor

#717 Update `dot-dsl` `practices`
  config.json
Labels: reputation/contributed_code/minor

#714 [German Sysadmin] Make sentence slightly friendlier
  exercises/concept/german-sysadmin/.docs/instructions.md
Labels: reputation/contributed_code/minor

#718 Remove all skips from concept exercise tests
  CONTRIBUTING.md
  exercises/concept/basketball-website/test/basketball_website_test.exs
  exercises/concept/bird-count/test/bird_count_test.exs
  exercises/concept/boutique-inventory/test/boutique_inventory_test.exs
  exercises/concept/boutique-suggestions/test/boutique_suggestions_test.exs
  exercises/concept/bread-and-potions/test/rpg_test.exs
  exercises/concept/captains-log/test/captains_log_test.exs
  exercises/concept/city-office/test/form_test.exs
  exercises/concept/community-garden/test/community_garden_test.exs
  exercises/concept/date-parser/test/date_parser_test.exs
  exercises/concept/dna-encoding/test/dna_test.exs
  exercises/concept/file-sniffer/test/file_sniffer_test.exs
  exercises/concept/freelancer-rates/test/freelancer_rates_test.exs
  exercises/concept/german-sysadmin/test/username_test.exs
  exercises/concept/guessing-game/test/guessing_game_test.exs
  exercises/concept/high-school-sweetheart/test/high_school_sweetheart_test.exs
  exercises/concept/high-score/test/high_score_test.exs
  exercises/concept/kitchen-calculator/test/kitchen_calculator_test.exs
  exercises/concept/language-list/test/language_list_test.exs
  exercises/concept/lasagna/test/lasagna_test.exs
  exercises/concept/library-fees/test/library_fees_test.exs
  exercises/concept/log-level/test/log_level_test.exs
  exercises/concept/lucas-numbers/test/lucas_numbers_test.exs
  exercises/concept/mensch-aergere-dich-nicht/test/mensch_aergere_dich_nicht_test.exs
  exercises/concept/name-badge/test/name_badge_test.exs
  exercises/concept/pacman-rules/test/rules_test.exs
  exercises/concept/remote-control-car/test/remote_control_car_test.exs
  exercises/concept/rpg-character-sheet/test/rpg/character_sheet_test.exs
  exercises/concept/rpn-calculator-inspection/test/rpn_calculator_inspection_test.exs
  exercises/concept/rpn-calculator-output/test/rpn_calculator/output_test.exs
  exercises/concept/rpn-calculator/test/rpn_calculator_test.exs
  exercises/concept/secrets/test/secrets_test.exs
  exercises/concept/stack-underflow/test/rpn_calculator/exception_test.exs
  exercises/concept/take-a-number/test/take_a_number_test.exs
  exercises/concept/wine-cellar/test/wine_cellar_test.exs
Labels: reputation/contributed_code/minor

#721 🤖 Add Ace editor and highlightjs languages to config.json
  config.json
Labels: reputation/contributed_code/minor, v3-migration 🤖
