Repository exercism/elixir, pull requests merged in 2021-02, with the labels that each got.

#594 Add track-specific docs
  exercises/shared/.docs/debug.md
  exercises/shared/.docs/help.md
  exercises/shared/.docs/tests.md
Labels: documentation 📖, v3 🌿

#595 New concept exercise `dates-and-time`
  concepts/dates-and-time/about.md
  concepts/dates-and-time/introduction.md
  concepts/dates-and-time/links.json
  concepts/erlang-libraries/about.md
  config.json
  exercises/concept/library-fees/.docs/hints.md
  exercises/concept/library-fees/.docs/instructions.md
  exercises/concept/library-fees/.docs/introduction.md
  exercises/concept/library-fees/.formatter.exs
  exercises/concept/library-fees/.gitignore
  exercises/concept/library-fees/.meta/config.json
  exercises/concept/library-fees/.meta/design.md
  exercises/concept/library-fees/.meta/exemplar.ex
  exercises/concept/library-fees/lib/library_fees.ex
  exercises/concept/library-fees/mix.exs
  exercises/concept/library-fees/test/library_fees_test.exs
  exercises/concept/library-fees/test/test_helper.exs
Labels: concept exercise 🌿, v3 🌿

#604 Bring `binary` up to date with canonical data
  exercises/practice/binary/.meta/example.ex
  exercises/practice/binary/.meta/version
  exercises/practice/binary/lib/binary.ex
  exercises/practice/binary/test/binary_test.exs
Labels: canonical sync 🔄

#605 Bring `binary-search-tree` up to date with canonical data
  exercises/practice/binary-search-tree/.meta/version
  exercises/practice/binary-search-tree/test/binary_search_tree_test.exs
Labels: canonical sync 🔄

#606 Bring `change` up to date with canonical data
  exercises/practice/change/.meta/tests.toml
  exercises/practice/change/.meta/version
  exercises/practice/change/test/change_test.exs
Labels: canonical sync 🔄

#611 Bring `difference-of-squares` up to date with canonical data
  exercises/practice/difference-of-squares/.meta/version
  exercises/practice/difference-of-squares/test/difference_of_squares_test.exs
Labels: canonical sync 🔄

#612 Bring `dnd-character` up to date with canonical-data
  exercises/practice/dnd-character/.meta/tests.toml
  exercises/practice/dnd-character/.meta/version
  exercises/practice/dnd-character/test/dnd_character_test.exs
Labels: canonical sync 🔄

#614 Bring `flatten-array` up to date with canonical data
  exercises/practice/flatten-array/.meta/version
  exercises/practice/flatten-array/test/flatten_array_test.exs
Labels: canonical sync 🔄

#613 Bring `etl` up to date with canonical data
  exercises/practice/etl/.meta/example.ex
  exercises/practice/etl/.meta/version
  exercises/practice/etl/lib/etl.ex
  exercises/practice/etl/test/etl_test.exs
Labels: canonical sync 🔄

#616 Bring `gigasecond` up to date with canonical data
  exercises/practice/gigasecond/.meta/version
  exercises/practice/gigasecond/lib/gigasecond.ex
  exercises/practice/gigasecond/test/gigasecond_test.exs
Labels: canonical sync 🔄

#617 Bring `grep` up to date with canonical data
  exercises/practice/grep/.meta/version
  exercises/practice/grep/test/grep_test.exs
Labels: canonical sync 🔄

#620 Deprecate `binary` and `hexadecimal` in favor of `all-your-base`
  config.json
  exercises/practice/hexadecimal/.meta/version
Labels: canonical sync 🔄

#607 Bring `clock` up to date with canonical data
  exercises/practice/clock/.meta/example.ex
  exercises/practice/clock/.meta/version
  exercises/practice/clock/test/clock_test.exs
Labels: canonical sync 🔄

#608 Bring `connect` up to date with canonical data
  exercises/practice/connect/.meta/version
  exercises/practice/connect/test/connect_test.exs
Labels: canonical sync 🔄

#609 Bring `custom-set` up to date with canonical data
  exercises/practice/custom-set/.meta/version
  exercises/practice/custom-set/test/custom_set_test.exs
Labels: canonical sync 🔄

#610 Bring `diamond` up to date with canonical data
  exercises/practice/diamond/.meta/version
  exercises/practice/diamond/test/diamond_test.exs
Labels: canonical sync 🔄

#619 Bring `hamming` up to date with canonical data
  exercises/practice/hamming/.meta/example.ex
  exercises/practice/hamming/.meta/tests.toml
  exercises/practice/hamming/.meta/version
  exercises/practice/hamming/test/hamming_test.exs
Labels: canonical sync 🔄

#621 Bring `isbn-verifier` up to date with canonical data
  exercises/practice/isbn-verifier/.meta/version
  exercises/practice/isbn-verifier/test/isbn_verifier_test.exs
Labels: canonical sync 🔄

#623 Bring `kindergarten-garden` up to date with canonical data
  exercises/practice/kindergarten-garden/.meta/version
  exercises/practice/kindergarten-garden/test/garden_test.exs
Labels: canonical sync 🔄

#624 Bring `largest-series-product` up to date with canonical data
  exercises/practice/largest-series-product/.meta/version
  exercises/practice/largest-series-product/test/largest_series_product_test.exs
Labels: canonical sync 🔄

#625 Bring `leap` up to date with canonical data
  exercises/practice/leap/.meta/version
  exercises/practice/leap/test/leap_test.exs
  exercises/practice/leap/test/year_test.exs
Labels: canonical sync 🔄

#627 Bring `luhn` up to date with canonical data
  exercises/practice/luhn/.meta/version
  exercises/practice/luhn/test/luhn_test.exs
Labels: canonical sync 🔄

#630 Bring `matrix` up to date with canonical data
  exercises/practice/matrix/.meta/example.ex
  exercises/practice/matrix/.meta/version
  exercises/practice/matrix/test/matrix_test.exs
Labels: canonical sync 🔄

#622 Bring `isogram` up to date with canonical data
  exercises/practice/isogram/.meta/version
  exercises/practice/isogram/test/isogram_test.exs
Labels: canonical sync 🔄

#618 🤖 Add file patterns to config.json
  config.json
Labels: v3-migration 🤖

#631 Bring `meetup` up to date with canonical data
  exercises/practice/meetup/.meta/version
  exercises/practice/meetup/test/meetup_test.exs
Labels: canonical sync 🔄

#633 Bring `minesweeper` up to date with canonical data
  exercises/practice/minesweeper/.meta/version
  exercises/practice/minesweeper/test/minesweeper_test.exs
Labels: canonical sync 🔄

#637 Bring `pangram` up to date with canonical data
  exercises/practice/pangram/.meta/version
  exercises/practice/pangram/test/pangram_test.exs
Labels: canonical sync 🔄

#638 Bring `pascals-triangle` up to date with canonical data
  exercises/practice/pascals-triangle/.meta/version
  exercises/practice/pascals-triangle/test/pascals_triangle_test.exs
Labels: canonical sync 🔄

#635 Bring `nucleotide-count` up to date with canonical data
  exercises/practice/nucleotide-count/.meta/design.md
  exercises/practice/nucleotide-count/.meta/tests.toml
  exercises/practice/nucleotide-count/.meta/version
  exercises/practice/nucleotide-count/test/nucleotide_count_test.exs
Labels: canonical sync 🔄

#634 Bring `nth-prime` up to date with canonical data
  exercises/practice/nth-prime/.meta/example.ex
  exercises/practice/nth-prime/.meta/version
  exercises/practice/nth-prime/test/nth_prime_test.exs
Labels: canonical sync 🔄

#641 Bring `prime-factors` up to date with canonical data
  exercises/practice/prime-factors/.meta/version
  exercises/practice/prime-factors/test/prime_factors_test.exs
Labels: canonical sync 🔄

#640 Bring `pig-latin` up to date with canonical data
  exercises/practice/pig-latin/.meta/example.ex
  exercises/practice/pig-latin/.meta/version
  exercises/practice/pig-latin/lib/pig_latin.ex
  exercises/practice/pig-latin/test/pig_latin_test.exs
Labels: canonical sync 🔄

#626 Bring `list-ops` up to date with canonical data
  config.json
  exercises/practice/list-ops/.meta/example.ex
  exercises/practice/list-ops/.meta/tests.toml
  exercises/practice/list-ops/.meta/version
  exercises/practice/list-ops/lib/list_ops.ex
  exercises/practice/list-ops/test/list_ops_test.exs
Labels: canonical sync 🔄

#639 Bring `phone-number` up to date with canonical data
  config.json
  exercises/practice/phone-number/.meta/config.json
  exercises/practice/phone-number/.meta/design.md
  exercises/practice/phone-number/.meta/example.ex
  exercises/practice/phone-number/.meta/version
  exercises/practice/phone-number/lib/phone.ex
  exercises/practice/phone-number/test/phone_test.exs
Labels: canonical sync 🔄

#651 Bring `sieve` up to date with canonical data
  exercises/practice/sieve/.meta/example.ex
  exercises/practice/sieve/.meta/version
  exercises/practice/sieve/test/sieve_test.exs
Labels: canonical sync 🔄

#654 Bring `sum-of-multiples` up to date with canonical data
  exercises/practice/sum-of-multiples/.meta/example.ex
  exercises/practice/sum-of-multiples/.meta/version
  exercises/practice/sum-of-multiples/test/sum_of_multiples_test.exs
Labels: canonical sync 🔄

#653 Bring `space-age` up to date with canonical data
  exercises/practice/space-age/.meta/version
  exercises/practice/space-age/test/space_age_test.exs
Labels: canonical sync 🔄

#644 Bring `rail-fence-cipher` up to date with canonical data
  exercises/practice/rail-fence-cipher/.meta/version
  exercises/practice/rail-fence-cipher/test/rail_fence_cipher_test.exs
Labels: canonical sync 🔄

#645 Bring `raindrops` up to date with canonical data
  exercises/practice/raindrops/.meta/version
  exercises/practice/raindrops/test/raindrops_test.exs
Labels: canonical sync 🔄

#647 Bring `robot-simulator` up to date with canonical data
  exercises/practice/robot-simulator/.meta/version
  exercises/practice/robot-simulator/test/robot_simulator_test.exs
Labels: canonical sync 🔄

#649 Bring `scrabble-score` up to date with canonical data
  exercises/practice/scrabble-score/.meta/version
  exercises/practice/scrabble-score/test/scrabble_test.exs
Labels: canonical sync 🔄

#650 Bring `series` up to date with canonical data
  exercises/practice/series/.meta/design.md
  exercises/practice/series/.meta/tests.toml
  exercises/practice/series/.meta/version
  exercises/practice/series/test/string_series_test.exs
Labels: canonical sync 🔄

#648 Bring `saddle-points` up to date with canonical data
  exercises/practice/saddle-points/.meta/example.ex
  exercises/practice/saddle-points/.meta/version
  exercises/practice/saddle-points/test/saddle_points_test.exs
Labels: canonical sync 🔄

#656 Bring `transpose` up to date with canonical data
  exercises/practice/transpose/.meta/example.ex
  exercises/practice/transpose/.meta/version
  exercises/practice/transpose/test/transpose_test.exs
Labels: canonical sync 🔄

#655 Bring `tournament` up to date with canonical data
  exercises/practice/tournament/.meta/version
  exercises/practice/tournament/test/tournament_test.exs
Labels: canonical sync 🔄

#657 Bring `twelve-days` up to date with canonical data
  exercises/practice/twelve-days/.meta/version
  exercises/practice/twelve-days/test/twelve_days_test.exs
Labels: canonical sync 🔄

#658 Bring `two-fer` up to date with canonical data
  exercises/practice/two-fer/.meta/version
  exercises/practice/two-fer/test/two_fer_test.exs
Labels: canonical sync 🔄

#659 Bring `word-count` up to date with canonical data
  config.json
  exercises/practice/word-count/.meta/example.ex
  exercises/practice/word-count/.meta/version
  exercises/practice/word-count/test/word_count_test.exs
Labels: canonical sync 🔄

#628 Bring `markdown` up to date with canonical data
  exercises/practice/markdown/.meta/example.ex
  exercises/practice/markdown/.meta/version
  exercises/practice/markdown/lib/markdown.ex
  exercises/practice/markdown/test/markdown_test.exs
Labels: canonical sync 🔄

#672 Bring `triangle` up to date with canonical data
  exercises/practice/triangle/.docs/design.md
  exercises/practice/triangle/.meta/tests.toml
  exercises/practice/triangle/.meta/version
  exercises/practice/triangle/test/triangle_test.exs
Labels: canonical sync 🔄

#671 Bring `sublist` up to date with canonical data
  exercises/practice/sublist/.meta/version
  exercises/practice/sublist/test/sublist_test.exs
Labels: canonical sync 🔄

#663 Bring `grade-school` up to date with canonical data
  exercises/practice/grade-school/.meta/example.ex
  exercises/practice/grade-school/.meta/tests.toml
  exercises/practice/grade-school/.meta/version
  exercises/practice/grade-school/test/school_test.exs
Labels: canonical sync 🔄

#662 Bring `zipper` up to date with canonical data
  exercises/practice/zipper/.meta/version
  exercises/practice/zipper/test/zipper_test.exs
Labels: canonical sync 🔄

#646 Bring `rna-transcription` up to date with canonical data
  exercises/practice/rna-transcription/.meta/version
  exercises/practice/rna-transcription/test/rna_transcription_test.exs
Labels: canonical sync 🔄

#642 Bring `protein-translation` up to date with canonical data
  exercises/practice/protein-translation/.meta/version
  exercises/practice/protein-translation/test/protein_translation_test.exs
Labels: canonical sync 🔄

#629 Bring `matching-brackets` up to date with canonical data
  exercises/practice/matching-brackets/.meta/version
  exercises/practice/matching-brackets/test/matching_brackets_test.exs
Labels: canonical sync 🔄

#636 Bring `palindrome-products` up to date with canonical data
  config.json
  exercises/practice/palindrome-products/.meta/example.ex
  exercises/practice/palindrome-products/.meta/version
  exercises/practice/palindrome-products/test/palindrome_products_test.exs
Labels: canonical sync 🔄

#615 Bring `forth` up to date with canonical data
  exercises/practice/forth/.meta/example.ex
  exercises/practice/forth/.meta/version
  exercises/practice/forth/test/forth_test.exs
Labels: canonical sync 🔄
