Repository exercism/elixir, pull requests merged in 2021-09, with the labels that each got.

#862 Date parser: fix typo (date -> day)
  exercises/concept/date-parser/.docs/instructions.md
Labels: x:size/tiny

#864 Credit michallepicki for #857 (city-office)
  exercises/concept/city-office/.meta/config.json
Labels: x:size/tiny

#865 Add clarifications for "round up/down" in freelancer rates
  exercises/concept/freelancer-rates/.docs/instructions.md
Labels: x:size/tiny

#869 Rational numbers: Update pow_real spec to integer to align with tests
  exercises/practice/rational-numbers/lib/rational_numbers.ex
Labels: x:size/small

#870 Update hints.md
  exercises/concept/secrets/.docs/hints.md
Labels: x:size/tiny

#872 Mention in `newsletter` instructions to close the log file
  exercises/concept/newsletter/.docs/instructions.md
Labels: x:size/tiny

#878 Remove duplicate `@type acc` definition in ListOps
  exercises/practice/list-ops/lib/list_ops.ex
Labels: x:size/small

#875 Correct arity of language-list functions
  exercises/concept/language-list/.docs/instructions.md
  exercises/concept/language-list/test/language_list_test.exs
Labels: x:size/small

#874 Correct WineCellar.filter examples
  exercises/concept/wine-cellar/.docs/instructions.md
Labels: x:size/small

#881 Fix ambiguity (plural forms) in kitchen-calculator exercise
  exercises/concept/kitchen-calculator/.docs/instructions.md
  exercises/concept/kitchen-calculator/test/kitchen_calculator_test.exs
Labels: x:size/small

#883 Fix update_score function name in instructions.md
  exercises/concept/high-score/.docs/instructions.md
Labels: x:size/tiny

#877 End two-fer test sentences with dot
  exercises/practice/two-fer/.meta/example.ex
  exercises/practice/two-fer/test/two_fer_test.exs
Labels: x:size/small

#888 Update instructions.md for "Log Level" exercise
  exercises/concept/log-level/.docs/instructions.md
Labels: x:size/tiny

#893 Fixed typo in High Score exercise section 5 description
  exercises/concept/high-score/.docs/instructions.md
Labels: x:size/tiny

#894 Fixed example format in German Sysadmin exercise
  exercises/concept/german-sysadmin/.docs/instructions.md
Labels: x:size/small

#895 Fixed typo in Date Parser exercise section 2 description
  exercises/concept/date-parser/.docs/instructions.md
Labels: x:size/tiny

#897 Fixed name of function in Basketball Website exercise.
  exercises/concept/basketball-website/.docs/instructions.md
Labels: x:size/small

#896 Fixed extra comman in Boutique Inventory exercise section 2 example
  exercises/concept/boutique-inventory/.docs/instructions.md
Labels: x:size/tiny

#904 docs(guessing-game): fix type in test descriptions
  exercises/concept/guessing-game/test/guessing_game_test.exs
Labels: x:size/small

#909 rpg-character-sheet: improve testing on IO.inspect's label
  exercises/concept/rpg-character-sheet/test/rpg/character_sheet_test.exs
Labels: bug 🐛, x:size/small

#911 Remove Agent memoization from `book-store`
  exercises/practice/book-store/.meta/example.ex
Labels: bug 🐛, x:size/tiny

#913 #907 - Date Parser - Removed a line from instructions to better match the tests
  exercises/concept/date-parser/.docs/instructions.md
Labels: x:size/tiny

#918 Explain why we don't accept instruction changes
  CONTRIBUTING.md
Labels: x:size/small

#919 Fix, elem/1 -> elem/2
  concepts/tuples/introduction.md
Labels: x:size/tiny

#920 Fix, elem/1 -> elem/2 in exercise
  exercises/concept/kitchen-calculator/.docs/introduction.md
Labels: x:size/tiny

#923 Fix `trap exists` typo across docs
  concepts/links/about.md
  concepts/links/introduction.md
  exercises/concept/rpn-calculator-inspection/.docs/introduction.md
Labels: x:size/small

#924 minor readability suggestions for File Sniffer instructions
  exercises/concept/file-sniffer/.docs/instructions.md
Labels: x:size/small

#922 Mention that concept exercise tests should be stand alone
  .github/pr-commenter.yml
  CONTRIBUTING.md
Labels: x:size/small

#931 Fix typo on Introduction
  concepts/typespecs/introduction.md
  exercises/concept/city-office/.docs/introduction.md
Labels: x:size/small

#934 City office fixes
  exercises/concept/city-office/.docs/instructions.md
  exercises/concept/city-office/.meta/exemplar.ex
  exercises/concept/city-office/test/form_test.exs
Labels: x:size/small

#936 fix test description
  exercises/concept/boutique-inventory/test/boutique_inventory_test.exs
Labels: x:size/small

#939 Add test and modify test description in `boutique-inventory`
  exercises/concept/boutique-inventory/test/boutique_inventory_test.exs
Labels: x:size/tiny, x:module/concept-exercise
