Repository exercism/elixir, pull requests merged in 2022-01, with the labels that each got.

#1022 Fix tiny typo in stack-underflow instructions
  exercises/concept/stack-underflow/.docs/instructions.md
Labels: x:size/tiny

#1024 `rational-numbers` test: Small cleanup
  exercises/practice/rational-numbers/test/rational_numbers_test.exs
Labels: x:size/small

#1031 Typo in instructions
  exercises/concept/basketball-website/.docs/instructions.md
Labels: x:size/tiny

#1033 Sync roman-numerals
  exercises/practice/roman-numerals/.meta/tests.toml
  exercises/practice/roman-numerals/test/roman_numerals_test.exs
Labels: x:size/small

#1032 Deprecate accumulate
  config.json
Labels: x:size/small

#1037 Sync queen-attack
  exercises/practice/queen-attack/.meta/tests.toml
  exercises/practice/queen-attack/test/queens_test.exs
Labels: x:size/small

#1038 Sync collatz-conjecture
  exercises/practice/collatz-conjecture/.meta/tests.toml
Labels: x:size/tiny

#1041 Set 5 seconds time limit for test to pass.
  exercises/concept/rpn-calculator-inspection/test/rpn_calculator_inspection_test.exs
Labels: x:size/small

#1049 Sync: Add exercise to `scale-generator`
  exercises/practice/scale-generator/.meta/tests.toml
  exercises/practice/scale-generator/test/scale_generator_test.exs
Labels: x:size/small

#1048 Sync: small updates to 5 exercises
  exercises/practice/accumulate/.meta/tests.toml
  exercises/practice/forth/.meta/tests.toml
  exercises/practice/forth/test/forth_test.exs
  exercises/practice/hello-world/.docs/instructions.md
  exercises/practice/pangram/.meta/tests.toml
  exercises/practice/pangram/test/pangram_test.exs
  exercises/practice/zipper/.meta/tests.toml
  exercises/practice/zipper/test/zipper_test.exs
Labels: x:size/medium

#1044 Sync: Adding one new test case to `isbn_verifier`
  exercises/practice/isbn-verifier/.meta/tests.toml
  exercises/practice/isbn-verifier/test/isbn_verifier_test.exs
Labels: x:size/small

#1046 Sync: Update test in `largest-series-product`
  exercises/practice/largest-series-product/.meta/tests.toml
Labels: x:size/tiny

#1045 Sync: Add one test case to `bowling`
  exercises/practice/bowling/.meta/tests.toml
  exercises/practice/bowling/test/bowling_test.exs
Labels: x:size/small

#1047 Sync: Add error handling to `space-age`
  config.json
  exercises/practice/space-age/.meta/example.ex
  exercises/practice/space-age/.meta/tests.toml
  exercises/practice/space-age/lib/space_age.ex
  exercises/practice/space-age/test/space_age_test.exs
Labels: x:size/small

#1050 Sync: re-write `grade-school`
  config.json
  exercises/practice/grade-school/.meta/config.json
  exercises/practice/grade-school/.meta/example.ex
  exercises/practice/grade-school/.meta/tests.toml
  exercises/practice/grade-school/lib/school.ex
  exercises/practice/grade-school/test/school_test.exs
Labels: x:size/large
