Repository exercism/elixir, pull requests merged in 2022-04, with the labels that each got.

#1105 Run older Elixir with OTP 21 instead of 20
  .github/workflows/ci.yml
  .github/workflows/pr.ci.yml
  README.md
Labels: x:size/tiny

#1103 New concept exercise `dancing-dots` (`use` and `behaviour`)
  concepts/behaviours/.meta/config.json
  concepts/behaviours/about.md
  concepts/behaviours/introduction.md
  concepts/behaviours/links.json
  concepts/use/.meta/config.json
  concepts/use/about.md
  concepts/use/introduction.md
  concepts/use/links.json
  config.json
  exercises/concept/dancing-dots/.docs/hints.md
  exercises/concept/dancing-dots/.docs/instructions.md
  exercises/concept/dancing-dots/.docs/introduction.md
  exercises/concept/dancing-dots/.formatter.exs
  exercises/concept/dancing-dots/.gitignore
  exercises/concept/dancing-dots/.meta/config.json
  exercises/concept/dancing-dots/.meta/design.md
  exercises/concept/dancing-dots/.meta/exemplar.ex
  exercises/concept/dancing-dots/lib/dancing_dots/animation.ex
  exercises/concept/dancing-dots/lib/dancing_dots/dot.ex
  exercises/concept/dancing-dots/lib/dancing_dots/dot_group.ex
  exercises/concept/dancing-dots/mix.exs
  exercises/concept/dancing-dots/test/dancing_dots/animation_test.exs
  exercises/concept/dancing-dots/test/test_helper.exs
Labels: x:size/large

#1108 Log-level: fix a typo with the function arity
  exercises/concept/log-level/test/log_level_test.exs
Labels: x:size/small

#1107 Add a dancing-dots test for defoverridable
  exercises/concept/dancing-dots/test/dancing_dots/animation_test.exs
Labels: x:size/small

#1109 `genserver` concept exercise improvements after solving it on my own on the platform
  concepts/genserver/.meta/config.json
  concepts/genserver/about.md
  concepts/genserver/introduction.md
  exercises/concept/take-a-number-deluxe/.docs/hints.md
  exercises/concept/take-a-number-deluxe/.docs/instructions.md
  exercises/concept/take-a-number-deluxe/.docs/introduction.md
  exercises/concept/take-a-number-deluxe/.meta/config.json
  exercises/concept/take-a-number-deluxe/.meta/design.md
Labels: x:size/tiny

#1111 Fix a => an in lasagna docs
  exercises/concept/lasagna/.docs/hints.md
  exercises/concept/lasagna/.docs/instructions.md
Labels: x:size/tiny

#1113 add Elixir School - OTP Concurrency to links.json
  concepts/genserver/links.json
Labels: x:size/small

#1116 New practice exercise `killer-sudoku-helper`
  config.json
  exercises/practice/killer-sudoku-helper/.docs/instructions.md
  exercises/practice/killer-sudoku-helper/.formatter.exs
  exercises/practice/killer-sudoku-helper/.gitignore
  exercises/practice/killer-sudoku-helper/.meta/config.json
  exercises/practice/killer-sudoku-helper/.meta/example.ex
  exercises/practice/killer-sudoku-helper/.meta/tests.toml
  exercises/practice/killer-sudoku-helper/lib/killer_sudoku_helper.ex
  exercises/practice/killer-sudoku-helper/mix.exs
  exercises/practice/killer-sudoku-helper/test/killer_sudoku_helper_test.exs
  exercises/practice/killer-sudoku-helper/test/test_helper.exs
Labels: x:size/large, x:type/coding, x:module/practice-exercise

#1115 New practice exercise `state-of-tic-tac-toe`
  bin/bootstrap_practice_exercise.exs
  config.json
  exercises/practice/state-of-tic-tac-toe/.docs/instructions.md
  exercises/practice/state-of-tic-tac-toe/.formatter.exs
  exercises/practice/state-of-tic-tac-toe/.gitignore
  exercises/practice/state-of-tic-tac-toe/.meta/config.json
  exercises/practice/state-of-tic-tac-toe/.meta/example.ex
  exercises/practice/state-of-tic-tac-toe/.meta/tests.toml
  exercises/practice/state-of-tic-tac-toe/lib/state_of_tic_tac_toe.ex
  exercises/practice/state-of-tic-tac-toe/mix.exs
  exercises/practice/state-of-tic-tac-toe/test/state_of_tic_tac_toe_test.exs
  exercises/practice/state-of-tic-tac-toe/test/test_helper.exs
Labels: x:size/large, x:type/coding, x:module/practice-exercise

#1123 Fix small typo in the Modules intro
  concepts/basics/introduction.md
  exercises/concept/lasagna/.docs/introduction.md
Labels: x:size/tiny
