Repository exercism/elixir, pull requests merged in 2022-10, with the labels that each got.

#1210 Add representer documentation
  docs/REPRESENTER_NORMALIZATIONS.md
  docs/config.json
  exercises/shared/.docs/representations.md
Labels: x:type/docs, x:module/representer

#1169 Add more tests to `say`
  exercises/practice/say/.meta/config.json
  exercises/practice/say/.meta/tests.toml
  exercises/practice/say/test/say_test.exs
Labels: hacktoberfest-accepted

#1212 Updated meetup instructions
  exercises/practice/matching-brackets/.meta/tests.toml
  exercises/practice/matching-brackets/test/matching_brackets_test.exs
  exercises/practice/meetup/.docs/instructions.md
Labels: canonical sync 🔄, x:size/small, hacktoberfest-accepted

#1223 Add missing spaces in `input` of `rectangles`
  exercises/practice/rectangles/test/rectangles_test.exs
Labels: x:size/tiny

#1222 fix typo
  concepts/use/.meta/config.json
  concepts/use/about.md
  concepts/use/introduction.md
  exercises/concept/dancing-dots/.docs/introduction.md
Labels: x:size/tiny, x:type/docs, hacktoberfest-accepted
